 const cleaningpack = [
    { id: 1, 
      name: "Vulval Toilet Cleaning Pack 1", 
      image: "/cleaning-pack5.png",
    availability: "200 in stock",
    sku: "MIN-606-M",
    remark: "For general and minor surgical use",
    description: "General purpose sterile kit for minor surgical and emergency procedures."},
    { 
      id: 2, 
      name: "Vulval Toilet Cleaning Pack 2", 
      image: "/cleaning-pack.png",
      availability: "200 in stock",
    sku: "MIN-606-M",
    remark: "For general and minor surgical use",
    description: "General purpose sterile kit for minor surgical and emergency procedures."
    },
    { 
      id: 3, 
      name: "Vulval Toilet Cleaning Pack 3", 
      image: "/cleaning-pack.png",
    availability: "200 in stock",
    sku: "MIN-606-M",
    remark: "For general and minor surgical use",
    description: "General purpose sterile kit for minor surgical and emergency procedures." },
    { 
      id: 4, 
      name: "Vulval Toilet Cleaning Pack 4", 
      image: "/cleaning-pack3.png",
    availability: "200 in stock",
    sku: "MIN-606-M",
    remark: "For general and minor surgical use",
    description: "General purpose sterile kit for minor surgical and emergency procedures." },
    { 
      id: 5, 
      name: "Vulval Toilet Cleaning Pack 5", 
      image: "/cleaning-pack5.png",
    availability: "200 in stock",
    sku: "MIN-606-M",
    remark: "For general and minor surgical use",
    description: "General purpose sterile kit for minor surgical and emergency procedures." },
    { 
      id: 6, 
      name: "Vulval Toilet Cleaning Pack 6", 
      image: "/cleaning-pack4.png",
    availability: "200 in stock",
    sku: "MIN-606-M",
    remark: "For general and minor surgical use",
    description: "General purpose sterile kit for minor surgical and emergency procedures." },
    { 
      id: 7, 
      name: "Vulval Toilet Cleaning Pack 7", 
      image: "/cleaning-pack3.png",
    availability: "200 in stock",
    sku: "MIN-606-M",
    remark: "For general and minor surgical use",
    description: "General purpose sterile kit for minor surgical and emergency procedures."},
  ];
export default cleaningpack;